version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16
    working_directory: ~/react-preschool
    steps:
      - checkout
      - run:
          name: 'Install Dependencies'
          command: |
            echo Installing Dependencies
            yarn install
      - run:
          name: 'Build Project'
          command: yarn build
      - save_cache:
          paths: 
            - build
          key: v1-build-{{ .Revision }}
  
  deploy:
    docker:
      - image: circleci/node:16
    working_directory: ~/react-preschool
    steps:
      - checkout
      - run:
          name: 'Setup repository' 
          command: |
            echo Commencing deploy to GitHub Pages
            git config --global user.email "msbrime@gmail.com"
            git config --global user.name "msbrime"
            git checkout --orphan gh-pages
            shopt -s extglob
            sudo rm -rf !('index.html'|'build') && sudo rm -f .gitignore .eslintrc.js .env.sample
      - add_ssh_keys:
          fingerprints:
            - 3a:4c:e8:18:0d:ec:72:ae:b5:e7:5a:fd:06:21:74:16
      - restore_cache:
          keys:
            - v1-build-{{ .Revision }}
      - run:
          name: 'Deploy to GitHub Pages' 
          command: |
            git add -f .
            git commit -m "CircleCI build $CIRCLE_BUILD_NUM from $CIRCLE_BRANCH"
            git push -f origin gh-pages
            echo 'Site successfully deployed to GitHub Pages'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop
      - deploy:
          requires: 
            - build
          filters:
            branches:
              only:
                - master
